#!/usr/bin/env node
/*
  seeds/seedDatabase.js

  - Generates SQL to create tables and insert sample data (trails, users, reviews, categories)
  - If env var DATABASE_URL is set and `psql` is available, it pipes SQL to psql to execute
  - Otherwise it writes seeds/seed.sql for manual execution and prints instructions

  Usage:
    DATABASE_URL="postgresql://user:pass@host:port/db" node seeds/seedDatabase.js

  Note: This script uses the system `psql` client when DATABASE_URL is provided. No additional Node DB libs required.
*/

const fs = require('fs');
const { spawnSync } = require('child_process');
const path = require('path');

const outSqlPath = path.resolve(__dirname, 'seed.sql');

// --- Sample data (derived from previous constants) ---
const trails = [
  { name: "Tà Năng - Phan Dũng", location: "Binh Thuan", difficulty: 'Expert', length_km: 55, duration_hr: 24, rating: 4.9, imageUrl: 'https://picsum.photos/seed/tanang/800/600', lat: 11.53, lng: 108.6 },
  { name: "Fansipan Peak", location: "Sa Pa", difficulty: 'Expert', length_km: 20, duration_hr: 18, rating: 4.8, imageUrl: 'https://picsum.photos/seed/fansipan/800/600', lat: 22.304, lng: 103.775 },
  { name: "Langbiang Mountain", location: "Da Lat", difficulty: 'Intermediate', length_km: 8, duration_hr: 5, rating: 4.6, imageUrl: 'https://picsum.photos/seed/langbiang/800/600', lat: 12.055, lng: 108.438 },
  { name: "Cuc Phuong Park", location: "Ninh Binh", difficulty: 'Beginner', length_km: 7, duration_hr: 3, rating: 4.5, imageUrl: 'https://picsum.photos/seed/cucphuong/800/600', lat: 20.316, lng: 105.613 },
];

// generate more trails by small variations to reach ~20
for (let i = 5; i <= 20; i++) {
  const base = trails[(i - 1) % trails.length];
  trails.push({
    name: `${base.name} Route ${i}`,
    location: base.location,
    difficulty: i % 3 === 0 ? 'Intermediate' : (i % 3 === 1 ? 'Expert' : 'Beginner'),
    length_km: Math.round(base.length_km * (0.6 + (i % 5) * 0.12)),
    duration_hr: Math.round(base.duration_hr * (0.5 + (i % 4) * 0.25)),
    rating: +(4.0 + (i % 5) * 0.2).toFixed(1),
    imageUrl: `https://picsum.photos/seed/trail${i}/800/600`,
    lat: base.lat + (i * 0.01),
    lng: base.lng + (i * 0.01),
  });
}

const users = [
  { name: 'Gia Huy', email: 'giahuy@example.com' },
  { name: 'An Nguyen', email: 'an@example.com' },
  { name: 'Binh Le', email: 'binh@example.com' },
  { name: 'Chi Pham', email: 'chi@example.com' },
  { name: 'Dung Tran', email: 'dung@example.com' },
  { name: 'Hoa Mai', email: 'hoa@example.com' },
  { name: 'Long Vu', email: 'long@example.com' },
  { name: 'Mai Linh', email: 'maih@example.com' },
  { name: 'Quynh Le', email: 'quynh@example.com' },
  { name: 'Minh Hoang', email: 'minh@example.com' },
];

const sampleComments = [
  'Absolutely breathtaking! A must-do.',
  'Challenging but rewarding. Be prepared.',
  'Great for a day trip. Nice view.',
  'The summit was surreal, worth it.',
  'Family friendly and enjoyable.',
  'Watch out for muddy sections after rain.',
  'Bring warm clothes for high altitude.',
  'Good signage and trail maintenance.',
  'Busy on weekends, go early.',
  'Amazing sunrise from the ridge.',
];

// create ~30 reviews distributed across trails and users
const reviews = [];
for (let i = 0; i < 30; i++) {
  const trailId = (i % trails.length) + 1; // will map to inserted trail ids
  const userId = (i % users.length) + 1; // map to user ids
  reviews.push({ trailId, userId, rating: 3 + (i % 3), comment: sampleComments[i % sampleComments.length] });
}

const categories = ['Beginner', 'Intermediate', 'Expert'];

// build SQL
let sql = `-- Seed script generated by seeds/seedDatabase.js\n\n`;
sql += `BEGIN;\n\n`;

sql += `-- Create tables if they do not exist\n`;
sql += `CREATE TABLE IF NOT EXISTS users (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  email TEXT UNIQUE,\n  avatar_url TEXT,\n  total_km INTEGER DEFAULT 0,\n  avg_altitude INTEGER DEFAULT 0,\n  avg_time_hr NUMERIC DEFAULT 0,\n  role TEXT DEFAULT 'user'\n);\n\n`;

sql += `CREATE TABLE IF NOT EXISTS trails (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  location TEXT,\n  difficulty TEXT,\n  length_km NUMERIC,\n  duration_hr NUMERIC,\n  rating NUMERIC,\n  description TEXT,\n  image_url TEXT,\n  lat NUMERIC,\n  lng NUMERIC\n);\n\n`;

sql += `CREATE TABLE IF NOT EXISTS reviews (\n  id SERIAL PRIMARY KEY,\n  trail_id INTEGER REFERENCES trails(id) ON DELETE CASCADE,\n  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,\n  rating INTEGER,\n  comment TEXT\n);\n\n`;

sql += `CREATE TABLE IF NOT EXISTS trail_categories (\n  id SERIAL PRIMARY KEY,\n  name TEXT UNIQUE NOT NULL\n);\n\n`;

sql += `CREATE TABLE IF NOT EXISTS trail_category_map (\n  trail_id INTEGER REFERENCES trails(id) ON DELETE CASCADE,\n  category_id INTEGER REFERENCES trail_categories(id) ON DELETE CASCADE,\n  PRIMARY KEY(trail_id, category_id)\n);\n\n`;

// inserts for categories
categories.forEach((c) => {
  sql += `INSERT INTO trail_categories (name) VALUES ('${c.replace("'","''")}') ON CONFLICT (name) DO NOTHING;\n`;
});
sql += '\n';

// insert users
users.forEach((u, idx) => {
  const avatar = `https://picsum.photos/seed/${encodeURIComponent(u.name)}/100/100`;
  sql += `INSERT INTO users (name, email, avatar_url) VALUES ('${u.name.replace("'","''")}', '${u.email}', '${avatar}') ON CONFLICT (email) DO NOTHING;\n`;
});
sql += '\n';

// insert trails
trails.forEach((t, idx) => {
  const desc = (t.description || `${t.name} in ${t.location}`).replace("'","''");
  sql += `INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('${t.name.replace("'","''")}', '${t.location.replace("'","''")}', '${t.difficulty}', ${t.length_km}, ${t.duration_hr}, ${t.rating}, '${desc}', '${t.imageUrl}', ${t.lat}, ${t.lng});\n`;
});
sql += '\n';

// Map some trails to categories (simple round-robin)
sql += `-- Map trails to categories\n`;
sql += `WITH tc AS (SELECT id, name FROM trail_categories)\n`;
sql += `SELECT 1;\n`; // no-op to keep psql happy if needed
// We'll add mapping using procedural insertion after tables exist (we'll use simple inserts selecting IDs)
categories.forEach((c, idx) => {
  // assign every Nth trail to this category
  sql += `INSERT INTO trail_category_map (trail_id, category_id) SELECT t.id, tc.id FROM trails t, trail_categories tc WHERE tc.name = '${c.replace("'","''")}' AND (t.id % ${categories.length}) = ${idx};\n`;
});
sql += '\n';

// Insert reviews (we will map user and trails by id order)
reviews.forEach((r) => {
  const safeComment = r.comment.replace("'","''");
  sql += `INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (${r.trailId}, ${r.userId}, ${r.rating}, '${safeComment}');\n`;
});

sql += '\nCOMMIT;\n\n';

sql += `-- Verification queries\n`;
sql += `SELECT COUNT(*) AS trails_count FROM trails;\n`;
sql += `SELECT COUNT(*) AS users_count FROM users;\n`;
sql += `SELECT COUNT(*) AS reviews_count FROM reviews;\n`;

// write SQL to file first
fs.writeFileSync(outSqlPath, sql, 'utf8');
console.log(`Wrote SQL to ${outSqlPath}`);

const databaseUrl = process.env.DATABASE_URL || process.env.PGURI || process.env.PG_CONNECTION_STRING;

function which(cmd) {
  const res = spawnSync('which', [cmd]);
  return res.status === 0;
}

if (databaseUrl && which('psql')) {
  console.log('DATABASE_URL detected and psql available — executing SQL via psql...');
  // run: psql <DATABASE_URL> -v ON_ERROR_STOP=1 -f seeds/seed.sql
  const proc = spawnSync('psql', [databaseUrl, '-v', 'ON_ERROR_STOP=1', '-f', outSqlPath], { stdio: 'inherit' });
  if (proc.error || proc.status !== 0) {
    console.error('psql execution failed. See above output.');
    process.exit(proc.status || 1);
  } else {
    console.log('Seed executed successfully via psql.');
    process.exit(0);
  }
} else {
  if (!databaseUrl) console.log('No DATABASE_URL detected — not executing SQL automatically.');
  if (!which('psql')) console.log('`psql` not available on PATH — cannot execute SQL automatically.');
  console.log('\nYou can run the seed SQL manually with psql:');
  console.log('  psql <CONNECTION> -v ON_ERROR_STOP=1 -f', outSqlPath);
  console.log('or set DATABASE_URL and ensure psql is on PATH, then:');
  console.log('  DATABASE_URL="postgresql://user:pass@host:port/db" node seeds/seedDatabase.js');
  process.exit(0);
}
