-- Seed script generated by seeds/seedDatabase.js

BEGIN;

-- Create tables if they do not exist
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  avatar_url TEXT,
  total_km INTEGER DEFAULT 0,
  avg_altitude INTEGER DEFAULT 0,
  avg_time_hr NUMERIC DEFAULT 0,
  role TEXT DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS trails (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT,
  difficulty TEXT,
  length_km NUMERIC,
  duration_hr NUMERIC,
  rating NUMERIC,
  description TEXT,
  image_url TEXT,
  lat NUMERIC,
  lng NUMERIC
);

CREATE TABLE IF NOT EXISTS reviews (
  id SERIAL PRIMARY KEY,
  trail_id INTEGER REFERENCES trails(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  rating INTEGER,
  comment TEXT
);

CREATE TABLE IF NOT EXISTS trail_categories (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS trail_category_map (
  trail_id INTEGER REFERENCES trails(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES trail_categories(id) ON DELETE CASCADE,
  PRIMARY KEY(trail_id, category_id)
);

INSERT INTO trail_categories (name) VALUES ('Beginner') ON CONFLICT (name) DO NOTHING;
INSERT INTO trail_categories (name) VALUES ('Intermediate') ON CONFLICT (name) DO NOTHING;
INSERT INTO trail_categories (name) VALUES ('Expert') ON CONFLICT (name) DO NOTHING;

INSERT INTO users (name, email, avatar_url) VALUES ('Gia Huy', 'giahuy@example.com', 'https://picsum.photos/seed/Gia%20Huy/100/100') ON CONFLICT (email) DO NOTHING;
INSERT INTO users (name, email, avatar_url) VALUES ('An Nguyen', 'an@example.com', 'https://picsum.photos/seed/An%20Nguyen/100/100') ON CONFLICT (email) DO NOTHING;
INSERT INTO users (name, email, avatar_url) VALUES ('Binh Le', 'binh@example.com', 'https://picsum.photos/seed/Binh%20Le/100/100') ON CONFLICT (email) DO NOTHING;
INSERT INTO users (name, email, avatar_url) VALUES ('Chi Pham', 'chi@example.com', 'https://picsum.photos/seed/Chi%20Pham/100/100') ON CONFLICT (email) DO NOTHING;
INSERT INTO users (name, email, avatar_url) VALUES ('Dung Tran', 'dung@example.com', 'https://picsum.photos/seed/Dung%20Tran/100/100') ON CONFLICT (email) DO NOTHING;
INSERT INTO users (name, email, avatar_url) VALUES ('Hoa Mai', 'hoa@example.com', 'https://picsum.photos/seed/Hoa%20Mai/100/100') ON CONFLICT (email) DO NOTHING;
INSERT INTO users (name, email, avatar_url) VALUES ('Long Vu', 'long@example.com', 'https://picsum.photos/seed/Long%20Vu/100/100') ON CONFLICT (email) DO NOTHING;
INSERT INTO users (name, email, avatar_url) VALUES ('Mai Linh', 'maih@example.com', 'https://picsum.photos/seed/Mai%20Linh/100/100') ON CONFLICT (email) DO NOTHING;
INSERT INTO users (name, email, avatar_url) VALUES ('Quynh Le', 'quynh@example.com', 'https://picsum.photos/seed/Quynh%20Le/100/100') ON CONFLICT (email) DO NOTHING;
INSERT INTO users (name, email, avatar_url) VALUES ('Minh Hoang', 'minh@example.com', 'https://picsum.photos/seed/Minh%20Hoang/100/100') ON CONFLICT (email) DO NOTHING;

INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng', 'Binh Thuan', 'Expert', 55, 24, 4.9, 'Tà Năng - Phan Dũng in Binh Thuan', 'https://picsum.photos/seed/tanang/800/600', 11.53, 108.6);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Fansipan Peak', 'Sa Pa', 'Expert', 20, 18, 4.8, 'Fansipan Peak in Sa Pa', 'https://picsum.photos/seed/fansipan/800/600', 22.304, 103.775);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Langbiang Mountain', 'Da Lat', 'Intermediate', 8, 5, 4.6, 'Langbiang Mountain in Da Lat', 'https://picsum.photos/seed/langbiang/800/600', 12.055, 108.438);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Cuc Phuong Park', 'Ninh Binh', 'Beginner', 7, 3, 4.5, 'Cuc Phuong Park in Ninh Binh', 'https://picsum.photos/seed/cucphuong/800/600', 20.316, 105.613);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 5', 'Binh Thuan', 'Beginner', 33, 18, 4, 'Tà Năng - Phan Dũng Route 5 in Binh Thuan', 'https://picsum.photos/seed/trail5/800/600', 11.58, 108.64999999999999);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 6', 'Binh Thuan', 'Intermediate', 40, 24, 4.2, 'Tà Năng - Phan Dũng Route 6 in Binh Thuan', 'https://picsum.photos/seed/trail6/800/600', 11.59, 108.66);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 7', 'Binh Thuan', 'Expert', 46, 30, 4.4, 'Tà Năng - Phan Dũng Route 7 in Binh Thuan', 'https://picsum.photos/seed/trail7/800/600', 11.6, 108.66999999999999);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 8', 'Binh Thuan', 'Beginner', 53, 12, 4.6, 'Tà Năng - Phan Dũng Route 8 in Binh Thuan', 'https://picsum.photos/seed/trail8/800/600', 11.61, 108.67999999999999);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 9', 'Binh Thuan', 'Intermediate', 59, 18, 4.8, 'Tà Năng - Phan Dũng Route 9 in Binh Thuan', 'https://picsum.photos/seed/trail9/800/600', 11.62, 108.69);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 10', 'Binh Thuan', 'Expert', 33, 24, 4, 'Tà Năng - Phan Dũng Route 10 in Binh Thuan', 'https://picsum.photos/seed/trail10/800/600', 11.629999999999999, 108.69999999999999);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 11', 'Binh Thuan', 'Beginner', 40, 30, 4.2, 'Tà Năng - Phan Dũng Route 11 in Binh Thuan', 'https://picsum.photos/seed/trail11/800/600', 11.639999999999999, 108.71);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 12', 'Binh Thuan', 'Intermediate', 46, 12, 4.4, 'Tà Năng - Phan Dũng Route 12 in Binh Thuan', 'https://picsum.photos/seed/trail12/800/600', 11.649999999999999, 108.72);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 13', 'Binh Thuan', 'Expert', 53, 18, 4.6, 'Tà Năng - Phan Dũng Route 13 in Binh Thuan', 'https://picsum.photos/seed/trail13/800/600', 11.66, 108.72999999999999);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 14', 'Binh Thuan', 'Beginner', 59, 24, 4.8, 'Tà Năng - Phan Dũng Route 14 in Binh Thuan', 'https://picsum.photos/seed/trail14/800/600', 11.67, 108.74);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 15', 'Binh Thuan', 'Intermediate', 33, 30, 4, 'Tà Năng - Phan Dũng Route 15 in Binh Thuan', 'https://picsum.photos/seed/trail15/800/600', 11.68, 108.75);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 16', 'Binh Thuan', 'Expert', 40, 12, 4.2, 'Tà Năng - Phan Dũng Route 16 in Binh Thuan', 'https://picsum.photos/seed/trail16/800/600', 11.69, 108.75999999999999);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 17', 'Binh Thuan', 'Beginner', 46, 18, 4.4, 'Tà Năng - Phan Dũng Route 17 in Binh Thuan', 'https://picsum.photos/seed/trail17/800/600', 11.7, 108.77);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 18', 'Binh Thuan', 'Intermediate', 53, 24, 4.6, 'Tà Năng - Phan Dũng Route 18 in Binh Thuan', 'https://picsum.photos/seed/trail18/800/600', 11.709999999999999, 108.78);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 19', 'Binh Thuan', 'Expert', 59, 30, 4.8, 'Tà Năng - Phan Dũng Route 19 in Binh Thuan', 'https://picsum.photos/seed/trail19/800/600', 11.719999999999999, 108.78999999999999);
INSERT INTO trails (name, location, difficulty, length_km, duration_hr, rating, description, image_url, lat, lng) VALUES ('Tà Năng - Phan Dũng Route 20', 'Binh Thuan', 'Beginner', 33, 12, 4, 'Tà Năng - Phan Dũng Route 20 in Binh Thuan', 'https://picsum.photos/seed/trail20/800/600', 11.729999999999999, 108.8);

-- Map trails to categories
WITH tc AS (SELECT id, name FROM trail_categories)
SELECT 1;
INSERT INTO trail_category_map (trail_id, category_id) SELECT t.id, tc.id FROM trails t, trail_categories tc WHERE tc.name = 'Beginner' AND (t.id % 3) = 0;
INSERT INTO trail_category_map (trail_id, category_id) SELECT t.id, tc.id FROM trails t, trail_categories tc WHERE tc.name = 'Intermediate' AND (t.id % 3) = 1;
INSERT INTO trail_category_map (trail_id, category_id) SELECT t.id, tc.id FROM trails t, trail_categories tc WHERE tc.name = 'Expert' AND (t.id % 3) = 2;

INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (1, 1, 3, 'Absolutely breathtaking! A must-do.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (2, 2, 4, 'Challenging but rewarding. Be prepared.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (3, 3, 5, 'Great for a day trip. Nice view.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (4, 4, 3, 'The summit was surreal, worth it.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (5, 5, 4, 'Family friendly and enjoyable.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (6, 6, 5, 'Watch out for muddy sections after rain.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (7, 7, 3, 'Bring warm clothes for high altitude.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (8, 8, 4, 'Good signage and trail maintenance.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (9, 9, 5, 'Busy on weekends, go early.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (10, 10, 3, 'Amazing sunrise from the ridge.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (11, 1, 4, 'Absolutely breathtaking! A must-do.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (12, 2, 5, 'Challenging but rewarding. Be prepared.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (13, 3, 3, 'Great for a day trip. Nice view.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (14, 4, 4, 'The summit was surreal, worth it.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (15, 5, 5, 'Family friendly and enjoyable.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (16, 6, 3, 'Watch out for muddy sections after rain.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (17, 7, 4, 'Bring warm clothes for high altitude.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (18, 8, 5, 'Good signage and trail maintenance.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (19, 9, 3, 'Busy on weekends, go early.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (20, 10, 4, 'Amazing sunrise from the ridge.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (1, 1, 5, 'Absolutely breathtaking! A must-do.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (2, 2, 3, 'Challenging but rewarding. Be prepared.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (3, 3, 4, 'Great for a day trip. Nice view.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (4, 4, 5, 'The summit was surreal, worth it.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (5, 5, 3, 'Family friendly and enjoyable.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (6, 6, 4, 'Watch out for muddy sections after rain.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (7, 7, 5, 'Bring warm clothes for high altitude.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (8, 8, 3, 'Good signage and trail maintenance.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (9, 9, 4, 'Busy on weekends, go early.');
INSERT INTO reviews (trail_id, user_id, rating, comment) VALUES (10, 10, 5, 'Amazing sunrise from the ridge.');

COMMIT;

-- Verification queries
SELECT COUNT(*) AS trails_count FROM trails;
SELECT COUNT(*) AS users_count FROM users;
SELECT COUNT(*) AS reviews_count FROM reviews;
